$path="$($env:APPDATA)\Microsoft\Office"
$bak="$($path)\bak"
 
# Ensure this script doesn't overwrite original backups
if (-not (Test-Path $bak)) {
                # Take a backup of the autocorrect entries
                try {
                                mkdir $bak |out-null
                                copy "$path\*.acl" "$bak" |out-null
                }
                catch {
                                throw "Backup failed. Not continuing"
                                break
                }
 
                # Commit dastardliness
                $word = New-Object -ComObject word.application
                $word.visible = $false
                $entries = $word.AutoCorrect.entries
                $entries.add("air","heir") | out-null
                $entries.add("I'll","isle") | out-null
                $entries.add("all","awl") | out-null
                $entries.add("allowed","aloud") | out-null
                $entries.add("alter","altar") | out-null
                $entries.add("aren't","aunt") | out-null
                $entries.add("eight","ate") | out-null
                $entries.add("oral","aural") | out-null
                $entries.add("away","aweigh") | out-null
                $entries.add("or","awe") | out-null
                $entries.add("I","eye") | out-null
                $entries.add("bail","bale") | out-null
                $entries.add("bait","bate") | out-null
                $entries.add("baize","bays") | out-null
                $entries.add("bald","bawled") | out-null
                $entries.add("ball","bawl") | out-null
                $entries.add("banned","band") | out-null
                $entries.add("bear","bare") | out-null
                $entries.add("base","bass") | out-null
                $entries.add("bay","bey") | out-null
                $entries.add("bazaar","bizarre") | out-null
                $entries.add("be","bee") | out-null
                $entries.add("beach","beech") | out-null
                $entries.add("been","bean") | out-null
                $entries.add("beat","beet") | out-null
                $entries.add("berry","bury") | out-null
                $entries.add("birth","berth") | out-null
                $entries.add("byte","bight") | out-null
                $entries.add("build","billed") | out-null
                $entries.add("blue","blew") | out-null
                $entries.add("board","bored") | out-null
                $entries.add("bold","bowled") | out-null
                $entries.add("born","borne") | out-null
                $entries.add("boy","buoy") | out-null
                $entries.add("break","brake") | out-null
                $entries.add("bread","bred") | out-null
                $entries.add("but","butt") | out-null
                $entries.add("by","bye") | out-null
                $entries.add("caught","court") | out-null
                $entries.add("ceiling","sealing") | out-null
                $entries.add("cell","sell") | out-null
                $entries.add("sent","scent") | out-null
                $entries.add("serial","cereal") | out-null
                $entries.add("cheap","cheep") | out-null
                $entries.add("check","cheque") | out-null
                $entries.add("chord","cord") | out-null
                $entries.add("site","sight") | out-null
                $entries.add("coal","kohl") | out-null
                $entries.add("course","coarse") | out-null
                $entries.add("kernel","colonel") | out-null
                $entries.add("queue","cue") | out-null
                $entries.add("symbol","cymbol") | out-null
                $entries.add("dam","damn") | out-null
                $entries.add("days","daze") | out-null
                $entries.add("dear","deer") | out-null
                $entries.add("descent","dissent") | out-null
                $entries.add("desert","dessert") | out-null
                $entries.add("due","dew") | out-null
                $entries.add("die","dye") | out-null
                $entries.add("draft","draught") | out-null
                $entries.add("earn","urn") | out-null
                $entries.add("you","ewe") | out-null
                $entries.add("faint","feint") | out-null
                $entries.add("fair","fare") | out-null
                $entries.add("farther","father") | out-null
                $entries.add("feet","feat") | out-null
                $entries.add("few","phew") | out-null
                $entries.add("file","phial") | out-null
                $entries.add("find","fined") | out-null
                $entries.add("flex","flecks") | out-null
                $entries.add("fold","foaled") | out-null
                $entries.add("for","four") | out-null
                $entries.add("forward","foreword") | out-null
                $entries.add("fourth","forth") | out-null
                $entries.add("foul","fowl") | out-null
                $entries.add("gate","gait") | out-null
                $entries.add("jeans","genes") | out-null
                $entries.add("nor","gnaw") | out-null
                $entries.add("great","grate") | out-null
                $entries.add("greys","graze") | out-null
                $entries.add("grown","groan") | out-null
                $entries.add("guest","guessed") | out-null
                $entries.add("hail","hale") | out-null
                $entries.add("hair","hare") | out-null
                $entries.add("hall","haul") | out-null
                $entries.add("hey","hay") | out-null
                $entries.add("he'll","heal") | out-null
                $entries.add("here","hear") | out-null
                $entries.add("heard","herd") | out-null
                $entries.add("he'd","heed") | out-null
                $entries.add("hi","high") | out-null
                $entries.add("higher","hire") | out-null
                $entries.add("him","hymn") | out-null
                $entries.add("wholly","holey") | out-null
                $entries.add("our","hour") | out-null
                $entries.add("idle","idol") | out-null
                $entries.add("in","inn") | out-null
                $entries.add("it's","its") | out-null
                $entries.add("key","quay") | out-null
                $entries.add("knave","nave") | out-null
                $entries.add("need","knead") | out-null
                $entries.add("new","knew") | out-null
                $entries.add("night","knight") | out-null
                $entries.add("not","knot") | out-null
                $entries.add("no","know") | out-null
                $entries.add("knows","nose") | out-null
                $entries.add("lapse","laps") | out-null
                $entries.add("law","lore") | out-null
                $entries.add("leak","leek") | out-null
                $entries.add("lean","lien") | out-null
                $entries.add("lesson","lessen") | out-null
                $entries.add("liar","lyre") | out-null
                $entries.add("licence","license") | out-null
                $entries.add("liquor","licker") | out-null
                $entries.add("lie","lye") | out-null
                $entries.add("lieu","loo") | out-null
                $entries.add("links","lynx") | out-null
                $entries.add("load","lode") | out-null
                $entries.add("loan","lone") | out-null
                $entries.add("locks","lox") | out-null
                $entries.add("loop","loupe") | out-null
                $entries.add("loot","lute") | out-null
                $entries.add("made","maid") | out-null
                $entries.add("mail","male") | out-null
                $entries.add("main","mane") | out-null
                $entries.add("maze","maize") | out-null
                $entries.add("mall","maul") | out-null
                $entries.add("manner","manna") | out-null
                $entries.add("mark","marque") | out-null
                $entries.add("mask","masque") | out-null
                $entries.add("more","maw") | out-null
                $entries.add("mean","mien") | out-null
                $entries.add("meet","meat") | out-null
                $entries.add("medal","meddle") | out-null
                $entries.add("metal","mettle") | out-null
                $entries.add("metre","meter") | out-null
                $entries.add("might","mite") | out-null
                $entries.add("minor","miner") | out-null
                $entries.add("mind","mined") | out-null
                $entries.add("missed","mist") | out-null
                $entries.add("mode","mowed") | out-null
                $entries.add("more","moor") | out-null
                $entries.add("morning","mourning") | out-null
                $entries.add("muscle","mussel") | out-null
                $entries.add("none","nun") | out-null
                $entries.add("owed","ode") | out-null
                $entries.add("owe","oh") | out-null
                $entries.add("one","won") | out-null
                $entries.add("packed","pact") | out-null
                $entries.add("packs","pax") | out-null
                $entries.add("pail","pale") | out-null
                $entries.add("pain","pane") | out-null
                $entries.add("pair","pear") | out-null
                $entries.add("palette","palate") | out-null
                $entries.add("pause","paws") | out-null
                $entries.add("pawn","porn") | out-null
                $entries.add("pea","pee") | out-null
                $entries.add("piece","peace") | out-null
                $entries.add("peak","peek") | out-null
                $entries.add("pedal","peddle") | out-null
                $entries.add("peer","pier") | out-null
                $entries.add("pi","pie") | out-null
                $entries.add("place","plaice") | out-null
                $entries.add("plain","plane") | out-null
                $entries.add("please","pleas") | out-null
                $entries.add("plumb","plum") | out-null
                $entries.add("pole","poll") | out-null
                $entries.add("poof","pouffe") | out-null
                $entries.add("practice","practise") | out-null
                $entries.add("praise","prays") | out-null
                $entries.add("principal","principle") | out-null
                $entries.add("profit","prophet") | out-null
                $entries.add("rain","reign") | out-null
                $entries.add("raise","rays") | out-null
                $entries.add("wrap","rap") | out-null
                $entries.add("raw","roar") | out-null
                $entries.add("read","reed") | out-null
                $entries.add("real","reel") | out-null
                $entries.add("reek","wreak") | out-null
                $entries.add("rest","wrest") | out-null
                $entries.add("review","revue") | out-null
                $entries.add("room","rheum") | out-null
                $entries.add("right","write") | out-null
                $entries.add("ring","wring") | out-null
                $entries.add("road","rode") | out-null
                $entries.add("row","roe") | out-null
                $entries.add("role","roll") | out-null
                $entries.add("rude","rood") | out-null
                $entries.add("root","route") | out-null
                $entries.add("rows","rose") | out-null
                $entries.add("wrote","rote") | out-null
                $entries.add("rough","ruff") | out-null
                $entries.add("rouse","rows") | out-null
                $entries.add("rung","wrung") | out-null
                $entries.add("saver","savour") | out-null
                $entries.add("spade","spayed") | out-null
                $entries.add("sale","sail") | out-null
                $entries.add("sane","seine") | out-null
                $entries.add("source","sauce") | out-null
                $entries.add("saw","soar") | out-null
                $entries.add("seen","scene") | out-null
                $entries.add("see","sea") | out-null
                $entries.add("seem","seam") | out-null
                $entries.add("sees","seize") | out-null
                $entries.add("so","sew") | out-null
                $entries.add("shake","sheikh") | out-null
                $entries.add("shoe","shoo") | out-null
                $entries.add("side","sighed") | out-null
                $entries.add("sign","sine") | out-null
                $entries.add("synch","sink") | out-null
                $entries.add("slay","sleigh") | out-null
                $entries.add("slow","sloe") | out-null
                $entries.add("sole","soul") | out-null
                $entries.add("some","sum") | out-null
                $entries.add("son","sun") | out-null
                $entries.add("sort","sought") | out-null
                $entries.add("stayed","staid") | out-null
                $entries.add("stair","stare") | out-null
                $entries.add("stake","steak") | out-null
                $entries.add("stalk","stork") | out-null
                $entries.add("stationary","stationery") | out-null
                $entries.add("steal","steel") | out-null
                $entries.add("style","stile") | out-null
                $entries.add("story","storey") | out-null
                $entries.add("straight","strait") | out-null
                $entries.add("sweet","suite") | out-null
                $entries.add("swat","swot") | out-null
                $entries.add("tax","tacks") | out-null
                $entries.add("tail","tale") | out-null
                $entries.add("talk","torque") | out-null
                $entries.add("taught","tort") | out-null
                $entries.add("tee","tea") | out-null
                $entries.add("team","teem") | out-null
                $entries.add("tier","tear") | out-null
                $entries.add("teas","tease") | out-null
                $entries.add("turn","tern") | out-null
                $entries.add("there","their") | out-null
                $entries.add("through","threw") | out-null
                $entries.add("throws","throes") | out-null
                $entries.add("thrown","throne") | out-null
                $entries.add("time","thyme") | out-null
                $entries.add("tick","tic") | out-null
                $entries.add("tied","tide") | out-null
                $entries.add("tyre","tire") | out-null
                $entries.add("two","too") | out-null
                $entries.add("towed","toad") | out-null
                $entries.add("told","tolled") | out-null
                $entries.add("toll","tole") | out-null
                $entries.add("tough","tuff") | out-null
                $entries.add("waste","waist") | out-null
                $entries.add("wait","weight") | out-null
                $entries.add("wave","waive") | out-null
                $entries.add("wall","waul") | out-null
                $entries.add("war","wore") | out-null
                $entries.add("where","wear") | out-null
                $entries.add("warn","worn") | out-null
                $entries.add("what","watt") | out-null
                $entries.add("way","weigh") | out-null
                $entries.add("we","whee") | out-null
                $entries.add("week","weak") | out-null
                $entries.add("we'd","weed") | out-null
                $entries.add("we'll","wheel") | out-null
                $entries.add("weather","whether") | out-null
                $entries.add("we're","weir") | out-null
                $entries.add("were","whirr") | out-null
                $entries.add("wet","whet") | out-null
                $entries.add("which","witch") | out-null
                $entries.add("while","wile") | out-null
                $entries.add("wine","whine") | out-null
                $entries.add("world","whirled") | out-null
                $entries.add("white","wight") | out-null
                $entries.add("who's","whose") | out-null
                $entries.add("would","wood") | out-null
                $entries.add("your","yaw") | out-null
                $entries.add("you'll","yule") | out-null
                $word.Quit()
                $word = $null
                [gc]::collect()
                [gc]::WaitForPendingFinalizers()
                write-host "Done - mmmmwahahahahah"
                write-host "Restart Outlook to make changes take effect"
                write-host "Undo by copying $bak\*.acl to $path"
}
else        {
write-host "Nope - backups already exist"
}